### ISSUE TITLE
question on weights

### ISSUE THREAD

**Issue by zh1peng** [Gilles86/pydbm#1]
Hi, I spent days trying to figure out the algorithm behind the DBM with the help of the codes, when I looked at the code, it was a bit confusing for the following bit, is the alpha**(obs+1) a tiny bug?
If I understand that correctly, for obs=2,  the weight would be (1-alpha), (1-alpha)*alpha and alpha**2

```python
for age in np.arange(1, obs):
       weights[-1].append((1-self.alpha) * self.alpha**(age))
weights[-1].append(self.alpha**(obs+1))
```        
I saw the version history that you added 1 for obs, but I have no clue why the weight for obs=2 are (1-alpha), (1-alpha)*alpha and alpha**3.

**Comment by Gilles86** [comment]
Hey,

This was a while back! Cool that you found this. Please note I mostly made this for self-study and not necessarily for production by other scientists. 

I think you are right that this is a bug. In any case, the weights should add up to 1 and they only do so if the last weight is changed to self.alpha**(obs).

This also makes intuitive sense to me (but please note it has been about 2 years now). We want to weight the last beta-distribution that includes _all observations_ by the probability that the underlying distribution did not change even once, for self.n_observations times in a row. Agreed?

I updated the code in this commit:
https://github.com/Gilles86/pydbm/commit/097141c93d6b65188f4302facba47309afbd2186

Cheers

**Comment by zh1peng** [comment]
Thank you for the reply. 
This is the only code I could find online for DBM. It is very helpful to learn the algorithm. 
Before I use it in the analysis, I think I will double check the results with the paper author, will let you know how it goes. 

🎉

**Comment by Gilles86** [comment]
> Before I use it in the analysis, I think I will double check the results with the paper author, will let you know how it goes.

Cool! I'm curious to know.

I remember checking my results against the Matlab code of Angela (Yu). The correlation was not 1.0, but something like .99, so I just assumed those were a numerical rounding errors. The effect of this bug will be small anyway, since alpha**n wil go to zero quite quickly. 

Angela also used a slightly different approach. I think she estimated only one beta-distribution per trial and then did the Bayesian integral over the previous prior numerically (instead of calculating a huge weighted sum of beta-distributions like I do here). Maybe drop her an email if you don't have her code yet.
